from typing import Any

class Client:
    def __init__(self, client_id: str = "", clean_session: bool = True) -> None: ...
    def connect(self, host: str, port: int = 1883, keepalive: int = 60) -> None: ...
    def disconnect(self) -> None: ...
    def loop_start(self) -> None: ...
    def loop_stop(self) -> None: ...
    def subscribe(self, topic: str, qos: int = 0) -> None: ...
    def publish(self, topic: str, payload: Any = None, qos: int = 0, retain: bool = False) -> None: ...
    on_connect: Any
    on_message: Any
